[package]
name = "divebar"
version = "0.1.0"
edition = "2021"


[dependencies]
chrono = "0.4.22"
ctrlc = "3.2.3"
snafu = "0.7.1"
structopt = "0.3.26"
sysinfo = "0.25.3"
xcb = "1.1.1"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
debug = false
panic = "abort"
